# Basic set up for three package managers

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
      time: "21:07"
      # Use Japan Standard Time (UTC +09:00)
      timezone: "Asia/Tokyo"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: "Bundler"
    reviewers:
      - "afrin-titly"
